version: "3.9"

services:

  api:
    build: .
    container_name: category-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:7
    container_name: category-mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: category-redis
    restart: always
    ports:
      - "6379:6379"

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: always
    ports:
      - "5540:5540"
    depends_on:
      - redis

volumes:
  mongo_data: